<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>../../assets/windows/neptune.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Neptune.Core/Neptune.Core.csproj" />
    <Resource Include="../../assets/windows/neptune.ico" Link="neptune.ico" />
    <Resource Include="../../assets/windows/neptune-master.png" Link="neptune.png" />
  </ItemGroup>
</Project>
